/**
 * UI Layout Constants
 */

export const UI_LAYOUT = {
  HEADER_HEIGHT: 2,
  HEADER_SEPARATOR_TOP: 2,
  EVENT_AREA_TOP: 3,
  EVENT_AREA_HEIGHT: '100%-7',
  SEPARATOR_BOTTOM: 3,
  STATUS_BAR_BOTTOM: 2,
  KEY_GUIDE_BOTTOM: 1,
  CONTROL_BAR_BOTTOM: 0,
  DEFAULT_TERMINAL_WIDTH: 180,
  MAX_SEARCH_LENGTH: 40,
} as const;
